*** Variables ***
## Data
${email}        quochuy13se02@gmail.com
${password}     inkr$1395$

## Locator
${btn_signin}    //span[contains(text(), 'Sign in')]
${email_edit_text}     //input[@type='email']
${btn_continue}      //button[@type='submit']
${password_edit_text}     //input[@type='password']
${btn_login}    //span[contains(text(), 'Login')]
${icon_user}    //span[@class="anticon anticon-user"]

