trigger:
- main

jobs:
- job: 'Pineline_Robotframework'
  pool:
    vmImage: 'windows-2022'
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
    maxParallel: 1

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
    displayName: 'Use Python $(python.version)'

  - script:
      pip install robotframework robotframework-selenium2library
    displayName: 'Install dependencies'

  - powershell: robot --pythonpath . -x outputxunit.xml test
    continueOnError: true
    displayName: 'Run testcase inkr'
  
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: outputxunit.xml
      searchFolder: 'D:\a\1\s\'