# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-selenium2library
        pip install selenium
        pip install robotframework-seleniumlibrary
        pip install robotframework-excellib
        pip install webdriver-manager
        pip install openpyxl
    - name: Test with RobotFramework
      run: |
        robot -d test_report test/information
    - name: Upload Robot Report Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: robotframework-report
        path: test_report/   
    - name: Upload Excel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: robot-excel-output
        path: data/   
